// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5UjPvLuGtFEGVktKbH0XAB17bMy2TZI',
    appId: '1:773792054427:web:e3f7f6265f48c923175a3e',
    messagingSenderId: '773792054427',
    projectId: 'park-d104c',
    authDomain: 'park-d104c.firebaseapp.com',
    storageBucket: 'park-d104c.firebasestorage.app',
    measurementId: 'G-NJHHZCHYFJ',
    databaseURL: "https://park-d104c-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefqGyLHtomSK1MYCxjdXwcLNGXExsk5M',
    appId: '1:773792054427:android:2717a00889429e3e175a3e',
    messagingSenderId: '773792054427',
    projectId: 'park-d104c',
    storageBucket: 'park-d104c.firebasestorage.app',
    databaseURL: "https://park-d104c-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgFonWjIN4L6mz7ldrLQfrZAshLNwLdDA',
    appId: '1:773792054427:ios:1482ad584533ce4f175a3e',
    messagingSenderId: '773792054427',
    projectId: 'park-d104c',
    storageBucket: 'park-d104c.firebasestorage.app',
    iosBundleId: 'com.example.park',
    databaseURL: "https://park-d104c-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgFonWjIN4L6mz7ldrLQfrZAshLNwLdDA',
    appId: '1:773792054427:ios:1482ad584533ce4f175a3e',
    messagingSenderId: '773792054427',
    projectId: 'park-d104c',
    storageBucket: 'park-d104c.firebasestorage.app',
    iosBundleId: 'com.example.park',
    databaseURL: "https://park-d104c-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5UjPvLuGtFEGVktKbH0XAB17bMy2TZI',
    appId: '1:773792054427:web:206dd53e136cc3e0175a3e',
    messagingSenderId: '773792054427',
    projectId: 'park-d104c',
    authDomain: 'park-d104c.firebaseapp.com',
    storageBucket: 'park-d104c.firebasestorage.app',
    measurementId: 'G-KCVBRGJPHM',
    databaseURL: "https://park-d104c-default-rtdb.firebaseio.com/",
  );
}
